services:
  - type: web
    name: hrms-ai-service
    runtime: python
    region: oregon
    plan: free
    buildCommand: cd ai-service && pip install -r requirements.txt
    startCommand: cd ai-service && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12

  - type: web
    name: hrms-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: JWT_SECRET
        value: k6i7QBqIUT36LecOy/nw/tNOpvATbU17tCtiFkDKgLPZofR9JYA1GYERJ7iIzYzP0uaRNjAPgIwQMGeU/Tcvzw==
      - key: DATABASE_URL
        value: https://hvfxvxoqlvgksdtpaovj.supabase.co
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://hrms-frontend-ure6.onrender.com

  - type: web
    name: hrms-frontend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: VITE_API_URL
        value: https://hrms-backend-ce4a.onrender.com
      - key: VITE_AI_SERVICE_URL
        value: https://hrms-ai-service.onrender.com
    envVars:
      - key: NODE_VERSION
        value: 18.x